version: '3'

services:
  postgres_orders_db:
    image: postgres:latest
    container_name: orders-db
    networks:
      - micro-service-network
    environment:
      POSTGRES_DB: ORDERS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1

  postgres_order_client_db:
    image: postgres:latest
    container_name: orders-client-db
    networks:
      - micro-service-network
    environment:
      POSTGRES_DB: ORDERS_CLIENT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1

  activemq:
    image: symptoma/activemq:5.16.3
    container_name: activemq-container
    networks:
      - micro-service-network
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  order-service:
    build: ./orders
    container_name: order-service-container
    networks:
      - micro-service-network
    ports:
      - "8091:8091"
    depends_on:
      - postgres_orders_db
      - activemq
    environment:
      ORDERS_SPRING_DB_SCHEMA: ORDERS
      ORDERS_SPRING_DATASOURCE_URL: orders-db:5432
      ORDERS_SPRING_DATASOURCE_USERNAME: postgres
      ORDERS_SPRING_DATASOURCE_PASSWORD: 1
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq-container:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin

  order-client-service:
    build: ./orders-client
    container_name: order-client-service-container
    networks:
      - micro-service-network
    ports:
      - "8092:8092"
    depends_on:
      - postgres_order_client_db
      - activemq
    environment:
      ORDER_CLIENT_SPRING_DB_SCHEMA: ORDERS_CLIENT
      ORDER_CLIENT_SPRING_DATASOURCE_URL: orders-client-db:5432
      ORDER_CLIENT_SPRING_DATASOURCE_USERNAME: postgres
      ORDER_CLIENT_SPRING_DATASOURCE_PASSWORD: 1
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq-container:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin

networks:
  micro-service-network: